ASoC: atmel: Add ASRC driver
The Asynchronous Sample Rate Converter (ASRC) converts the sample rate of
an incoming audio frame without affecting quality. It supports input and
output sampling rates up to 192 kHz. It is made of 4 independent digital
signal processing modules (DSP). Each DSP can be configured with specific
input and output sampling frequencies and is associated to oneof the DMA
channels. Each DSP can process mono or stereo audio stream.
Data can be provided to the DSPs via up to four input channels and data
can be read from the DSPs via up to 4 output channels. A channel comprises
a holding register that can be accessed via software or via a channel of
the central DMA. The ASRC generates the trigger events for the central DMA.
Up to 8 channels are available.
Depending on the channel index and its configuration, a channel manages
from one up to eight audio frames. The ASRC can be configured to process
up to four stereo audio streams in a fully independent manner. Input/out
sampling frequencies differ for each DSP. The ASRC supports TDM audio
stream. ASRC is capable to concatenate/split audio streams while resampling
frequencies. The ASRC can be configured to resample and merge several
audio input sources of the same or of different sampling frequencies
carried by several DMA channels into a single output audio stream sampled
at a unique frequency and carried on a single DMA channel (TDM audio
stream creation from multiple sources). The ASRC can also split and
resample audio streams (e.g. TDM stream) carried on a single DMA channel
to multiple audio streams, each having the same or different resampling
frequencies.

Signed-off-by: Codrin Ciubotariu <codrin.ciubotariu@microchip.com>
(cherry picked from linux-6.6-trunk/at91/sound)
[andrei.simion: Fix initialization error:
error: initialization of ‘void (*)(struct platform_device *)’ from
incompatible pointer type ‘int (*)(struct platform_device *)’
[-Werror=incompatible-pointer-types]
Modify the of_property_for_each_u32() call acording to the new prototype
according to commit 9722c3b66e2]
Signed-off-by: Andrei Simion <andrei.simion@microchip.com>