soc: sifive: Fix build errors of the ccache pmu driver
Currently, ccache pmu driver is implemented in ccache driver
We need to make ccache depend on PERF_EVENTS config, otherwise
it will have build error as below:

drivers/soc/sifive/sifive_ccache.c: In function 'sifive_ccache_pmu_read':
drivers/soc/sifive/sifive_ccache.c:338:43: error: 'struct perf_event' has no member named 'hw'
  338 |         struct hw_perf_event *hwc = &event->hw;
      |                                           ^~
drivers/soc/sifive/sifive_ccache.c:341:22: error: 'struct hw_perf_event' has no member named 'idx'
  341 |         int idx = hwc->idx;
      |                      ^~

Signed-off-by: Eric Lin <eric.lin@sifive.com>