media: microchip-isc: add missing VIDEOBUF2_VMALLOC dependency
The microchip-isc-stats driver uses vb2_vmalloc_memops but doesn't
declare a dependency on VIDEOBUF2_VMALLOC, causing linker errors:

undefined reference to `vb2_vmalloc_memops'

Add the missing select statement to fix the build error.

Fixes: 53a2de0065f1 ("media: platform: microchip: Add new histogram submodule")
Signed-off-by: Balakrishnan Sambath <balakrishnan.s@microchip.com>